In [2]:
'''
Question 1:
Generate a 3x4 NumPy array with random integers between 1 and 50.   
a. Calculate and print the Mean, Median, and Standard Deviation of the array 
b. Print the Sum of all elements and the sum of each row. 
c. Reshape the 3x4 array into a 2x6 array and print it. 
'''
import numpy as np
import random
arr=np.random.randint(1,51,size=(3,4))
print(f"Original array is:\n{arr}")
mn=np.mean(arr)
md=np.median(arr)
dev=np.std(arr)
print(f"a.\nMean = {mn}\nMedian = {md}\nStandard Deviation = {dev}\n")
s=np.sum(arr)
s1=np.sum(arr,axis=1)
print(f"b.\nSum of all elements = {s}\nSum of each row:\n{s1}\n")
newarr=arr.reshape(2,6)
print(f"c. After reshaping into a 2x6 array:\n{newarr}")

Original array is:
[[22  6 45 33]
 [36 36 45 45]
 [29 26 39 43]]
a.
Mean = 33.75
Median = 36.0
Standard Deviation = 11.158890327148722

b.
Sum of all elements = 405
Sum of each row:
[106 162 137]

c. After reshaping into a 2x6 array:
[[22  6 45 33 36 36]
 [45 45 29 26 39 43]]


In [3]:
'''
Question 2:
Create two (3 * 3) matrices using NumPy and print it. 
Perform and print the results of the following linear algebra operations
a. Matrix addition 
b. Matrix subtraction 
c. Matrix multiplication (element-wise and dot product) 
d. Transpose of a matrix 
e. Determinant and inverse (if applicable)
'''
import numpy as np
a=input("Enter integer numbers for 3x3 matrix A: ").split()
b=input("Enter integer numbers for 3x3 matrix B: ").split()
arr1=np.array(a,dtype=int).reshape(3,3)
arr2=np.array(b,dtype=int).reshape(3,3)
print(f"Matrix A:\n{arr1}\nMatrix B:\n{arr2}\n")
s=np.add(arr1,arr2)
d=np.subtract(arr1,arr2)
p=np.multiply(arr1,arr2)
do=np.dot(arr1,arr2)
tr1=np.transpose(arr1)
tr2=np.transpose(arr2)
d1=np.linalg.det(arr1)
d2=np.linalg.det(arr2)
c1,c2=True,True

print(f"a.\nMatrix A + Matrix B=\n{s}\nb.\nMatrix A - Matrix B =\n{d}\nc.\nMatrix multiplication (element-wise) =\n{p}")
print(f"Matrix multiplication(dot product) =\n{do}")
print(f"d.\nTranspose of Matrix A =\n{tr1}\nTranspose of Matrix B =\n{tr2}\ne.\nDeterminant of Matrix A=\n{d1}\nDeterminant of Matrix B=\n{d2}")
try: 
    i1=np.linalg.inv(arr1)
except np.linalg.LinAlgError:
    print("Matrix A is not invertible.")
    c1=False
try: 
    i2=np.linalg.inv(arr2)
except np.linalg.LinAlgError:
    print("Matrix B is not invertible.")
    c2=False
if(c1): print(f"Inverse of Matrix A=\n{i1}")
if(c2): print(f"Inverse of Matrix B=\n{i2}")

Enter integer numbers for 3x3 matrix A: 1 0 0 0 1 0 0 0 1 
Enter integer numbers for 3x3 matrix B: 1 0 0 0 0 1 1 0 0
Matrix A:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Matrix B:
[[1 0 0]
 [0 0 1]
 [1 0 0]]

a.
Matrix A + Matrix B=
[[2 0 0]
 [0 1 1]
 [1 0 1]]
b.
Matrix A - Matrix B =
[[ 0  0  0]
 [ 0  1 -1]
 [-1  0  1]]
c.
Matrix multiplication (element-wise) =
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Matrix multiplication(dot product) =
[[1 0 0]
 [0 0 1]
 [1 0 0]]
d.
Transpose of Matrix A =
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Transpose of Matrix B =
[[1 0 1]
 [0 0 0]
 [0 1 0]]
e.
Determinant of Matrix A=
1.0
Determinant of Matrix B=
0.0
Matrix B is not invertible.
Inverse of Matrix A=
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
